// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6LWjPK2YY0A-0KV7gh8lZhP_BNA9UPp8',
    appId: '1:949648824522:web:21196fbecad9de6162bc33',
    messagingSenderId: '949648824522',
    projectId: 'muzic-zone',
    authDomain: 'muzic-zone.firebaseapp.com',
    storageBucket: 'muzic-zone.firebasestorage.app',
    measurementId: 'G-R47YBDED3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhH34zu63v58pjahImtStJto_nFkCD4bo',
    appId: '1:949648824522:android:87e7844613a98be062bc33',
    messagingSenderId: '949648824522',
    projectId: 'muzic-zone',
    storageBucket: 'muzic-zone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2hA7Xzxld58ATex09O0yo-iaCw5gmP8k',
    appId: '1:949648824522:ios:c9947fc2b6f8bd9b62bc33',
    messagingSenderId: '949648824522',
    projectId: 'muzic-zone',
    storageBucket: 'muzic-zone.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2hA7Xzxld58ATex09O0yo-iaCw5gmP8k',
    appId: '1:949648824522:ios:c9947fc2b6f8bd9b62bc33',
    messagingSenderId: '949648824522',
    projectId: 'muzic-zone',
    storageBucket: 'muzic-zone.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6LWjPK2YY0A-0KV7gh8lZhP_BNA9UPp8',
    appId: '1:949648824522:web:2c3e1f339f44d36262bc33',
    messagingSenderId: '949648824522',
    projectId: 'muzic-zone',
    authDomain: 'muzic-zone.firebaseapp.com',
    storageBucket: 'muzic-zone.firebasestorage.app',
    measurementId: 'G-8WPWLMZLR5',
  );
}
